import type {
  AIAnalysisRun,
  AIInsight,
  AITask,
  BuildingMemory,
  SourceEvidence,
} from "@/types/ai";

const now = new Date("2026-06-15T10:00:00Z");
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000);

export const mockBuildingMemories: BuildingMemory[] = [
  {
    id: "bm-demo",
    projectId: "proj-demo",
    summary:
      "A 1986 reinforced concrete frame government office in central Xi'an, vacant since 2019. The structure is generally sound with localized carbonation at column bases. Primary renovation challenges are obsolete MEP, non-compliant fire egress for assembly occupancy, deteriorating south facade, and incomplete documentation. Strong potential for adaptive reuse as a community cultural center with atrium insertion and ground-floor public activation.",
    knownFacts: [
      "8-story RC frame, 12,800 sqm GFA, built 1986",
      "Vacant since 2019; last major MEP renovation circa 2003",
      "South facade tile spalling on ~35% of elevation",
      "Roof waterproofing failed in multiple zones",
      "Single stair core; corridor widths below assembly code",
      "No accessible entrance; elevator non-compliant",
      "Structural inspection 2024: frame generally sound, carbonation at B1 column bases",
    ],
    missingInformation: [
      "Complete structural as-built drawings (only partial 1986 set uploaded)",
      "Verified stair evacuation width and exit capacity calculations",
      "Roof structural load capacity for potential rooftop garden",
      "MEP shaft sizing and vertical riser survey",
      "Hazardous materials (asbestos) survey report",
      "Geotechnical assessment for basement areas",
      "Fire engineering report for occupancy change to assembly",
      "Measured floor plans confirming corridor dimensions",
    ],
    keyRisks: [
      "Occupancy change from office to assembly triggers strict fire and egress requirements",
      "Falling facade debris — active safety hazard on south sidewalk",
      "Full MEP replacement required — schedule and cost driver",
      "Incomplete structural documentation increases design uncertainty",
      "Potential asbestos in 1980s floor finishes",
    ],
    renovationPotential:
      "High adaptive reuse potential. Central urban location, generous floor plates, and robust concrete frame support conversion to cultural hub. Atrium insertion on floors 1–3 could create landmark interior space. Ground floor public interface activation offers strong community value.",
    designConstraints: [
      "Must preserve primary concrete frame per owner brief",
      "Budget level: medium — limits deep structural modifications",
      "Temporary safety barriers required on south facade during design phase",
      "Heritage level: none — but 1980s civic architecture character should be considered",
      "Phased occupancy may be required given MEP replacement scope",
    ],
    ownerRequirements: [
      "Transform to public community cultural and learning hub",
      "Preserve main concrete structure where feasible",
      "Activate ground floor for public interface",
      "Improve accessibility to current standards",
      "Target medium budget with phased implementation option",
    ],
    importantDecisions: [
      "Proceed with adaptive reuse strategy evaluation (2026-06-01)",
      "Commission asbestos survey before any interior demolition",
      "Install safety netting on south facade — approved",
      "Structural engineer site visit scheduled for column base assessment",
    ],
    unresolvedQuestions: [
      "Can a new stair core be added on the east side without major structural intervention?",
      "Is rooftop terrace structurally feasible given current slab capacity?",
      "What phasing allows partial cultural programming during MEP replacement?",
      "Does the owner require preservation of original facade tile pattern?",
    ],
    lastUpdatedByAI: daysAgo(1),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: "insight-1",
    projectId: "proj-demo",
    title: "Missing structural as-built drawings",
    type: "missing_info",
    priority: "high",
    summary: "Only partial 1986 structural drawings uploaded. Floor plates, reinforcement details, and foundation records are incomplete.",
    evidence: "Document archive analysis — 1 of 4 expected structural drawing sets present",
    recommendation: "Request complete as-built set from original design institute or commission as-built survey.",
    confidence: 0.92,
    status: "open",
    sourceType: "document",
    sourceId: "doc-1",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    id: "insight-2",
    projectId: "proj-demo",
    title: "Verify stair evacuation width",
    type: "compliance_warning",
    priority: "critical",
    summary: "Measured corridor and stair widths may not satisfy GB 50016 requirements for assembly occupancy.",
    evidence: "Code review + site measurement notes; Diagnosis item: Non-compliant fire egress",
    recommendation: "Structural/fire engineer to verify egress capacity. Evaluate additional stair core on east side.",
    confidence: 0.88,
    status: "open",
    sourceType: "diagnosis",
    sourceId: "diag-4",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
  },
  {
    id: "insight-3",
    projectId: "proj-demo",
    title: "Atrium insertion opportunity",
    type: "opportunity",
    priority: "medium",
    summary: "Large floor plates on floors 1–3 support selective slab opening for double-height cultural space without compromising primary frame.",
    evidence: "Spatial analysis of 1986 typical floor plan; adaptive reuse precedent review",
    recommendation: "Develop concept study for atrium location. Verify beam capacity before schematic design.",
    confidence: 0.76,
    status: "open",
    sourceType: "document",
    sourceId: null,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
  {
    id: "insight-4",
    projectId: "proj-demo",
    title: "MEP shaft insufficiency risk",
    type: "risk",
    priority: "high",
    summary: "Existing vertical shafts may be undersized for new HVAC loads and cultural program requirements.",
    evidence: "MEP as-built (2003) vs. estimated new load calculations",
    recommendation: "Survey all MEP shafts. Plan shaft enlargement or new riser routing.",
    confidence: 0.84,
    status: "open",
    sourceType: "document",
    sourceId: "doc-4",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: "insight-5",
    projectId: "proj-demo",
    title: "Roof load verification needed",
    type: "missing_info",
    priority: "high",
    summary: "Rooftop garden or terrace proposed in deep recreation strategy — roof slab capacity unverified.",
    evidence: "Strategy Lab: Deep Recreation option; no roof structural calc on file",
    recommendation: "Commission roof load assessment before committing to rooftop program.",
    confidence: 0.91,
    status: "open",
    sourceType: "document",
    sourceId: null,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: "insight-6",
    projectId: "proj-demo",
    title: "Ground floor public interface activation",
    type: "design_strategy",
    priority: "medium",
    summary: "Removing ground floor partitions and adding transparent facade could create strong community entry and visibility.",
    evidence: "Urban context analysis; owner requirement for public cultural hub",
    recommendation: "Develop ground floor concept with stakeholder workshop. Coordinate with egress redesign.",
    confidence: 0.79,
    status: "acknowledged",
    sourceType: "document",
    sourceId: null,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
  },
  {
    id: "insight-7",
    projectId: "proj-demo",
    title: "Facade aging and exposed mechanical equipment",
    type: "risk",
    priority: "high",
    summary: "South elevation tile failure combined with visible rooftop and facade-mounted equipment degrades street presence.",
    evidence: "Survey photos (doc-2); Diagnosis: South facade tile spalling",
    recommendation: "Integrate facade renewal with MEP equipment screening in strategy selection.",
    confidence: 0.95,
    status: "open",
    sourceType: "photo",
    sourceId: "doc-2",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(3),
  },
  {
    id: "insight-8",
    projectId: "proj-demo",
    title: "Cost escalation from full MEP replacement",
    type: "cost_warning",
    priority: "high",
    summary: "Complete MEP replacement represents estimated 35–45% of medium renovation budget.",
    evidence: "Diagnosis: Obsolescent MEP systems (critical); comparable project benchmarks",
    recommendation: "Develop phased MEP plan. Consider energy retrofit bundling for grant eligibility.",
    confidence: 0.82,
    status: "open",
    sourceType: "diagnosis",
    sourceId: "diag-3",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: "insight-9",
    projectId: "proj-2",
    title: "Steel corrosion at ground level",
    type: "risk",
    priority: "critical",
    summary: "Active corrosion at steel frame base plates requires urgent structural assessment.",
    evidence: "Site inspection notes",
    recommendation: "Commission structural engineer site visit within 2 weeks.",
    confidence: 0.87,
    status: "open",
    sourceType: "site_issue",
    sourceId: null,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
];

export const mockAITasks: AITask[] = [
  {
    id: "task-1",
    projectId: "proj-demo",
    insightId: "insight-1",
    title: "Supplement structural as-built drawings",
    description: "Obtain complete structural drawing set or commission measured as-built survey.",
    category: "documentation",
    priority: "high",
    status: "pending",
    assignedToId: "user-1",
    dueDate: daysAgo(-14),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    id: "task-2",
    projectId: "proj-demo",
    insightId: "insight-2",
    title: "Verify stair evacuation width",
    description: "Measure all stair and corridor widths. Compare against assembly occupancy code requirements.",
    category: "fire_safety",
    priority: "critical",
    status: "in_progress",
    assignedToId: "user-2",
    dueDate: daysAgo(-7),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-3",
    projectId: "proj-demo",
    insightId: "insight-5",
    title: "Confirm roof load capacity",
    description: "Structural engineer to assess roof slab for potential rooftop garden or terrace loads.",
    category: "structure",
    priority: "high",
    status: "pending",
    assignedToId: "user-2",
    dueDate: daysAgo(-21),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-4",
    projectId: "proj-demo",
    insightId: "insight-4",
    title: "Survey existing MEP shafts",
    description: "Document shaft dimensions, routing, and capacity for new HVAC and electrical loads.",
    category: "mep",
    priority: "high",
    status: "pending",
    assignedToId: "user-2",
    dueDate: daysAgo(-10),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: "task-5",
    projectId: "proj-demo",
    insightId: "insight-7",
    title: "Take additional facade photos",
    description: "Complete north and east elevation photo survey. Document exposed mechanical equipment.",
    category: "survey",
    priority: "medium",
    status: "pending",
    assignedToId: "user-3",
    dueDate: daysAgo(-5),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-6",
    projectId: "proj-demo",
    insightId: null,
    title: "Review fire safety constraints with code consultant",
    description: "Engage fire engineering consultant for occupancy change analysis.",
    category: "compliance",
    priority: "high",
    status: "pending",
    assignedToId: null,
    dueDate: daysAgo(-18),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-7",
    projectId: "proj-demo",
    insightId: "insight-3",
    title: "Ask structural engineer to verify wall removal feasibility",
    description: "Identify non-structural partitions suitable for removal on floors 1–3 for atrium concept.",
    category: "structure",
    priority: "medium",
    status: "pending",
    assignedToId: "user-2",
    dueDate: daysAgo(-12),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
];

export const mockAnalysisRuns: AIAnalysisRun[] = [
  {
    id: "run-1",
    projectId: "proj-demo",
    analysisType: "building_memory_update",
    inputSummary: "Project metadata + 5 documents + 7 diagnosis items",
    outputSummary: "Updated building memory with 8 missing info items and 5 key risks",
    generatedItemCount: 1,
    modelName: "recrete-mock-v1",
    confidence: 0.89,
    createdAt: daysAgo(1),
  },
  {
    id: "run-2",
    projectId: "proj-demo",
    analysisType: "document_analysis",
    inputSummary: "5 uploaded documents analyzed",
    outputSummary: "Identified 3 missing document categories, generated 4 document summaries",
    generatedItemCount: 4,
    modelName: "recrete-mock-v1",
    confidence: 0.85,
    createdAt: daysAgo(3),
  },
  {
    id: "run-3",
    projectId: "proj-demo",
    analysisType: "diagnosis_generation",
    inputSummary: "Building memory + documents + site issues",
    outputSummary: "Generated 7 diagnosis items across 8 categories",
    generatedItemCount: 7,
    modelName: "recrete-mock-v1",
    confidence: 0.87,
    createdAt: daysAgo(15),
  },
  {
    id: "run-4",
    projectId: "proj-demo",
    analysisType: "strategy_generation",
    inputSummary: "7 diagnosis items + owner requirements",
    outputSummary: "Generated 3 renovation strategies with comparison metrics",
    generatedItemCount: 3,
    modelName: "recrete-mock-v1",
    confidence: 0.83,
    createdAt: daysAgo(8),
  },
  {
    id: "run-5",
    projectId: "proj-demo",
    analysisType: "cost_risk_estimation",
    inputSummary: "3 strategies + diagnosis severity matrix",
    outputSummary: "Risk matrix and phasing plan for adaptive reuse strategy",
    generatedItemCount: 2,
    modelName: "recrete-mock-v1",
    confidence: 0.78,
    createdAt: daysAgo(2),
  },
  {
    id: "run-6",
    projectId: "proj-demo",
    analysisType: "copilot_chat",
    inputSummary: "User query: main risks of this building",
    outputSummary: "Structured risk summary with 4 priority items",
    generatedItemCount: 0,
    modelName: "recrete-mock-v1",
    confidence: 0.91,
    createdAt: daysAgo(0),
  },
];

export const mockSourceEvidence: SourceEvidence[] = [
  {
    id: "ev-1",
    projectId: "proj-demo",
    sourceType: "document",
    sourceId: "doc-1",
    documentId: "doc-1",
    pageNumber: 3,
    locationLabel: "Foundation plan",
    quote: "Partial drawing set — floor plans missing for levels 4–8",
    boundingBox: null,
    confidence: 0.88,
    createdAt: daysAgo(20),
  },
  {
    id: "ev-2",
    projectId: "proj-demo",
    sourceType: "photo",
    sourceId: "doc-2",
    documentId: "doc-2",
    pageNumber: null,
    locationLabel: "South elevation, 3F",
    quote: "Visible tile debonding and exposed substrate",
    boundingBox: "0.32,0.15,0.68,0.45",
    confidence: 0.94,
    createdAt: daysAgo(18),
  },
];

export const documentAISummaries: Record<string, { aiSummary: string; extractedText?: string }> = {
  "doc-1": {
    aiSummary:
      "1986 RC frame structural drawings. Includes foundation plan and partial floor framing. Missing upper floor plans and reinforcement details.",
    extractedText: "REINFORCED CONCRETE FRAME — TYPICAL FLOOR 1986...",
  },
  "doc-2": {
    aiSummary:
      "42 site photos documenting south facade tile spalling, window deterioration, and exposed rooftop mechanical equipment.",
  },
  "doc-3": {
    aiSummary:
      "2024 third-party structural inspection. Frame generally sound. Carbonation detected at B1 column bases C-D/3-5. Recommend protective coating.",
    extractedText: "STRUCTURAL INSPECTION REPORT — COVER METER READINGS...",
  },
  "doc-4": {
    aiSummary:
      "Partial MEP as-built from 2003 renovation. HVAC capacity insufficient for assembly occupancy. Electrical panel at 65% capacity.",
  },
  "doc-5": {
    aiSummary:
      "Historical archive documenting government office usage 1986–2018 and minor interior renovations in 1998 and 2003.",
  },
};

export const missingDocumentCategories = [
  "Complete architectural as-built (all floors)",
  "Fire safety inspection records",
  "Hazardous materials survey",
  "Energy audit baseline",
  "Geotechnical report",
];

export function getProjectNextAction(projectId: string): string {
  const actions: Record<string, string> = {
    "proj-demo": "Verify stair evacuation width and complete structural drawing archive",
    "proj-2": "Urgent structural assessment for ground-level steel corrosion",
    "proj-3": "Complete envelope survey and energy audit",
    "proj-4": "Heritage facade condition assessment",
  };
  return actions[projectId] ?? "Run AI document analysis to improve data completeness";
}

export function getProjectTopRisk(projectId: string): string | null {
  const insight = mockAIInsights
    .filter((i) => i.projectId === projectId && (i.type === "risk" || i.type === "compliance_warning"))
    .sort((a, b) => {
      const order = { critical: 0, high: 1, medium: 2, low: 3 };
      return order[a.priority] - order[b.priority];
    })[0];
  return insight?.title ?? null;
}
