import type {
  CollaborationReview,
  ProjectStakeholder,
} from "@/types/collaboration";

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000);

export const mockStakeholders: ProjectStakeholder[] = [
  {
    id: "stk-1",
    projectId: "proj-demo",
    userId: "user-1",
    name: "Lin Wei",
    email: "lin.wei@recrete.io",
    role: "architect",
    party: "design_team",
    organization: "Recrete Studio",
    isLead: true,
    joinedAt: daysAgo(45),
  },
  {
    id: "stk-2",
    projectId: "proj-demo",
    userId: "user-2",
    name: "Chen Hao",
    email: "chen.hao@recrete.io",
    role: "engineer",
    party: "structure_consultant",
    organization: "Recrete Studio",
    isLead: true,
    joinedAt: daysAgo(40),
  },
  {
    id: "stk-3",
    projectId: "proj-demo",
    userId: "user-3",
    name: "Zhang Mei",
    email: "zhang.mei@recrete.io",
    role: "project_manager",
    party: "design_team",
    organization: "Recrete Studio",
    isLead: false,
    joinedAt: daysAgo(45),
  },
  {
    id: "stk-4",
    projectId: "proj-demo",
    userId: "user-4",
    name: "Wang Fang",
    email: "wang.fang@xian.gov.cn",
    role: "owner",
    party: "owner",
    organization: "Xi'an Cultural Bureau",
    isLead: true,
    joinedAt: daysAgo(30),
  },
  {
    id: "stk-5",
    projectId: "proj-demo",
    userId: "user-5",
    name: "Dr. Liu Ming",
    email: "liu.ming@heritage.cn",
    role: "consultant",
    party: "heritage_authority",
    organization: "Provincial Heritage Review Board",
    isLead: true,
    joinedAt: daysAgo(20),
  },
];

export const mockCollaborationReviews: CollaborationReview[] = [
  {
    id: "rev-1",
    projectId: "proj-demo",
    targetType: "strategy",
    targetId: "strat-2",
    targetTitle: "Medium Reconfiguration · 中度功能重组",
    status: "negotiating",
    requiredParties: ["owner", "design_team", "structure_consultant", "heritage_authority"],
    approvals: [
      { party: "design_team", approved: true, approvedBy: "Lin Wei", approvedAt: daysAgo(3), note: "方案可行，建议保留原入口比例" },
      { party: "structure_consultant", approved: true, approvedBy: "Chen Hao", approvedAt: daysAgo(2), note: "主体结构无需加固" },
      { party: "owner", approved: false, approvedBy: null, approvedAt: null, note: null },
      { party: "heritage_authority", approved: false, approvedBy: null, approvedAt: null, note: null },
    ],
    comments: [
      {
        id: "cmt-1",
        reviewId: "rev-1",
        authorId: "user-4",
        authorName: "Wang Fang",
        authorRole: "owner",
        party: "owner",
        content: "社区文化中心需要至少 800㎡ 的公共活动空间，当前方案仅 620㎡。请设计团队调整中庭挑空范围。",
        createdAt: daysAgo(2),
      },
      {
        id: "cmt-2",
        reviewId: "rev-1",
        authorId: "user-1",
        authorName: "Lin Wei",
        authorRole: "architect",
        party: "design_team",
        content: "可通过压缩后勤面积并开放二层连廊获得额外 200㎡ 公共面积，结构顾问已确认可行。",
        createdAt: daysAgo(1),
      },
      {
        id: "cmt-3",
        reviewId: "rev-1",
        authorId: "user-5",
        authorName: "Dr. Liu Ming",
        authorRole: "consultant",
        party: "heritage_authority",
        content: "原政府办公楼南立面砖雕需完整保留，不可新增大面积玻璃幕墙。",
        createdAt: daysAgo(1),
      },
    ],
    negotiationPoints: [
      {
        id: "neg-1",
        reviewId: "rev-1",
        topic: "公共活动空间面积",
        positions: [
          { party: "owner", stance: "≥800㎡ 公共活动空间", priority: "must_have" },
          { party: "design_team", stance: "通过连廊改造可达成 820㎡", priority: "preferred" },
        ],
        status: "open",
        resolution: null,
        updatedAt: daysAgo(1),
      },
      {
        id: "neg-2",
        reviewId: "rev-1",
        topic: "南立面风貌保护",
        positions: [
          { party: "heritage_authority", stance: "保留砖雕，限制幕墙比例 ≤15%", priority: "must_have" },
          { party: "design_team", stance: "接受限制，改用高窗采光", priority: "flexible" },
        ],
        status: "open",
        resolution: null,
        updatedAt: daysAgo(1),
      },
    ],
    dueDate: daysAgo(-7),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: "rev-2",
    projectId: "proj-demo",
    targetType: "diagnosis",
    targetId: "diag-3",
    targetTitle: "MEP System Obsolescence · 机电系统老化",
    status: "approved",
    requiredParties: ["design_team", "structure_consultant"],
    approvals: [
      { party: "design_team", approved: true, approvedBy: "Lin Wei", approvedAt: daysAgo(8) },
      { party: "structure_consultant", approved: true, approvedBy: "Chen Hao", approvedAt: daysAgo(7) },
    ],
    comments: [],
    negotiationPoints: [],
    dueDate: daysAgo(5),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(7),
  },
  {
    id: "rev-3",
    projectId: "proj-demo",
    targetType: "strategy",
    targetId: "strat-3",
    targetTitle: "Deep Recreation · 深度再造",
    status: "pending",
    requiredParties: ["owner", "design_team", "structure_consultant", "heritage_authority", "government"],
    approvals: [
      { party: "design_team", approved: false },
      { party: "structure_consultant", approved: false },
      { party: "owner", approved: false },
      { party: "heritage_authority", approved: false },
      { party: "government", approved: false },
    ],
    comments: [],
    negotiationPoints: [],
    dueDate: daysAgo(-14),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
];
