import type { RenovationCase } from "./case-library";

/** Additional cases to reach pilot-scale reference library (report target: 30+). */
export const extendedRenovationCases: RenovationCase[] = [
  {
    id: "case-8",
    title: "Nanjing Brick Warehouse Adaptive Reuse",
    location: "Nanjing",
    region: "华东",
    buildingType: "Industrial",
    structureType: "Brick masonry with timber roof",
    originalFunction: "Textile warehouse",
    targetFunction: "Startup incubator",
    constructionYear: 1972,
    grossFloorArea: 4200,
    strategyType: "adaptive_reuse",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 2400,
    durationMonths: 16,
    summary: "Timber roof reinforcement and selective brick opening enabled daylight-filled coworking without full structural replacement.",
    lessons: ["Timber truss survey was critical path", "Brick opening required temporary shoring"],
    tags: ["adaptive-reuse", "industrial", "nanjing", "structure", "heritage"],
  },
  {
    id: "case-9",
    title: "Wuhan Hospital Wing Conversion",
    location: "Wuhan",
    region: "华中",
    buildingType: "Healthcare",
    structureType: "Reinforced concrete frame",
    originalFunction: "Hospital ward",
    targetFunction: "Elderly care center",
    constructionYear: 1998,
    grossFloorArea: 11000,
    strategyType: "medium_renovation",
    outcome: "partial",
    costLevel: "high",
    costPerSqm: 3600,
    durationMonths: 22,
    summary: "MEP and infection-control upgrades dominated cost; structural frame adequate with localized slab openings only.",
    lessons: ["Medical MEP standards drive 40%+ of budget", "Infection control zoning reshaped circulation"],
    failureReasons: ["Medical gas riser replacement added 4 months"],
    tags: ["medium-renovation", "healthcare", "wuhan", "mep"],
  },
  {
    id: "case-10",
    title: "Suzhou Canal-side Heritage Workshop",
    location: "Suzhou",
    region: "华东",
    buildingType: "Heritage",
    structureType: "Wood and brick mixed",
    originalFunction: "Craft workshop",
    targetFunction: "Cultural exhibition",
    constructionYear: 1928,
    grossFloorArea: 1800,
    strategyType: "light_renewal",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 3100,
    durationMonths: 14,
    summary: "Reversible timber bracing and moisture control enabled exhibition use while preserving original roof structure.",
    lessons: ["Heritage review limited facade changes", "Moisture monitoring mandatory for timber"],
    tags: ["light-renewal", "heritage", "suzhou", "structure"],
  },
  {
    id: "case-11",
    title: "Chongqing Hillside School Retrofit",
    location: "Chongqing",
    region: "西南",
    buildingType: "Educational",
    structureType: "Reinforced concrete frame on slope",
    originalFunction: "Primary school",
    targetFunction: "Community learning center",
    constructionYear: 1991,
    grossFloorArea: 7200,
    strategyType: "medium_renovation",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 2700,
    durationMonths: 18,
    summary: "Foundation monitoring and retaining wall repair preceded interior MEP renewal on steep site.",
    lessons: ["Slope stability survey before any excavation", "Drainage upgrade prevented repeat settlement"],
    tags: ["medium-renovation", "education", "chongqing", "structure", "mep"],
  },
  {
    id: "case-12",
    title: "Dalian Cold Storage to Art Gallery",
    location: "Dalian",
    region: "东北",
    buildingType: "Industrial",
    structureType: "Precast concrete frame",
    originalFunction: "Cold storage",
    targetFunction: "Art gallery",
    constructionYear: 1984,
    grossFloorArea: 6500,
    strategyType: "deep_recreation",
    outcome: "partial",
    costLevel: "high",
    costPerSqm: 4100,
    durationMonths: 26,
    summary: "Insulation removal and precast connection strengthening were underestimated; gallery climate control added major MEP scope.",
    lessons: ["Precast connection survey essential", "Gallery HVAC doubles MEP cost vs office"],
    failureReasons: ["Precast corbel repair scope expanded mid-construction"],
    tags: ["deep-recreation", "industrial", "dalian", "structure", "mep"],
  },
  {
    id: "case-13",
    title: "Fuzhou Lane House Cluster Renewal",
    location: "Fuzhou",
    region: "华东",
    buildingType: "Residential",
    structureType: "Brick-wood traditional",
    originalFunction: "Residential",
    targetFunction: "Boutique hotel",
    constructionYear: 1965,
    grossFloorArea: 2400,
    strategyType: "adaptive_reuse",
    outcome: "success",
    costLevel: "high",
    costPerSqm: 5200,
    durationMonths: 20,
    summary: "Phased renewal of 12 courtyard units with fire compartmentation and hidden MEP achieved boutique hotel operation.",
    lessons: ["Fire compartmentation between units was governing constraint", "Hidden MEP routing preserved historic facades"],
    tags: ["adaptive-reuse", "heritage", "fuzhou", "fire", "mep"],
  },
  {
    id: "case-14",
    title: "Kunming Plateau Office Energy Retrofit",
    location: "Kunming",
    region: "西南",
    buildingType: "Office",
    structureType: "Reinforced concrete frame",
    originalFunction: "Office",
    targetFunction: "Green-certified office",
    constructionYear: 2004,
    grossFloorArea: 13500,
    strategyType: "facade_upgrade",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 1650,
    durationMonths: 9,
    summary: "Envelope-first retrofit with high-performance glazing and VRF replacement cut EUI by 38% without structural work.",
    lessons: ["VRF replacement ROI under 8 years at plateau climate", "Tenant stay-in phasing reduced vacancy"],
    tags: ["facade", "energy", "office", "kunming", "mep"],
  },
  {
    id: "case-15",
    title: "Harbin Soviet-era Civic Building",
    location: "Harbin",
    region: "东北",
    buildingType: "Civic",
    structureType: "Brick-concrete mixed frame",
    originalFunction: "Cultural club",
    targetFunction: "Youth activity center",
    constructionYear: 1956,
    grossFloorArea: 8900,
    strategyType: "medium_renovation",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 2950,
    durationMonths: 20,
    summary: "Seismic wall addition and roof insulation upgrade enabled winter occupancy in severe cold climate zone.",
    lessons: ["Severe cold climate drives envelope cost", "Roof insulation upgrade critical for heating load"],
    tags: ["medium-renovation", "civic", "harbin", "structure", "energy"],
  },
  {
    id: "case-16",
    title: "Shenzhen Factory Loft Live-work",
    location: "Shenzhen",
    region: "华南",
    buildingType: "Industrial",
    structureType: "Steel frame",
    originalFunction: "Electronics factory",
    targetFunction: "Live-work lofts",
    constructionYear: 1995,
    grossFloorArea: 18000,
    strategyType: "deep_recreation",
    outcome: "success",
    costLevel: "high",
    costPerSqm: 3900,
    durationMonths: 24,
    summary: "New vertical circulation cores and mezzanine inserts transformed wide-span factory into loft units with code-compliant egress.",
    lessons: ["Egress core count governed unit yield", "Mezzanine dead load required beam check"],
    tags: ["deep-recreation", "industrial", "shenzhen", "structure", "fire"],
  },
  {
    id: "case-17",
    title: "Taiyuan Government Annex Light Renewal",
    location: "Taiyuan",
    region: "华北",
    buildingType: "Office",
    structureType: "Reinforced concrete frame",
    originalFunction: "Government annex",
    targetFunction: "Public service hall",
    constructionYear: 1989,
    grossFloorArea: 5400,
    strategyType: "light_renewal",
    outcome: "success",
    costLevel: "low",
    costPerSqm: 1450,
    durationMonths: 7,
    summary: "Accessibility ramp, lobby reconfiguration, and localized MEP met public service requirements without structural change.",
    lessons: ["Accessibility ramp alignment with heritage streetscape needed early coordination"],
    tags: ["light-renewal", "office", "taiyuan", "accessibility"],
  },
  {
    id: "case-18",
    title: "Urumqi Market Hall Conversion",
    location: "Urumqi",
    region: "西北",
    buildingType: "Commercial",
    structureType: "Reinforced concrete frame",
    originalFunction: "Wholesale market hall",
    targetFunction: "Community market",
    constructionYear: 1993,
    grossFloorArea: 16000,
    strategyType: "adaptive_reuse",
    outcome: "partial",
    costLevel: "medium",
    costPerSqm: 2300,
    durationMonths: 19,
    summary: "Ventilation and fire separation upgrades for dense retail occupancy were more complex than anticipated.",
    lessons: ["Retail fire compartmentation drives layout", "Natural ventilation insufficient for new density"],
    failureReasons: ["Smoke exhaust redesign delayed opening by 2 months"],
    tags: ["adaptive-reuse", "commercial", "urumqi", "fire", "mep"],
  },
  {
    id: "case-19",
    title: "Qingdao Pier Warehouse Hotel",
    location: "Qingdao",
    region: "华东",
    buildingType: "Industrial",
    structureType: "Steel and brick mixed",
    originalFunction: "Port warehouse",
    targetFunction: "Harbor-view hotel",
    constructionYear: 1936,
    grossFloorArea: 11200,
    strategyType: "deep_recreation",
    outcome: "success",
    costLevel: "high",
    costPerSqm: 4800,
    durationMonths: 32,
    summary: "Salt corrosion repair on steel structure and marine-grade envelope enabled boutique hotel on historic pier site.",
    lessons: ["Marine corrosion survey on all steel connections", "Salt spray zone envelope spec mandatory"],
    tags: ["deep-recreation", "industrial", "qingdao", "structure", "heritage"],
  },
  {
    id: "case-20",
    title: "Hefei Research Park Office Refresh",
    location: "Hefei",
    region: "华东",
    buildingType: "Office",
    structureType: "Reinforced concrete frame",
    originalFunction: "R&D office",
    targetFunction: "Tech campus hub",
    constructionYear: 2008,
    grossFloorArea: 22000,
    strategyType: "light_renewal",
    outcome: "success",
    costLevel: "low",
    costPerSqm: 1100,
    durationMonths: 6,
    summary: "Interior reconfiguration and smart building overlay achieved tech campus branding at low capex intensity.",
    lessons: ["Smart building overlay cheaper than full MEP replacement for 2000s buildings"],
    tags: ["light-renewal", "office", "hefei", "mep"],
  },
  {
    id: "case-21",
    title: "Lanzhou Plateau Hospital Clinic Wing",
    location: "Lanzhou",
    region: "西北",
    buildingType: "Healthcare",
    structureType: "Reinforced concrete frame",
    originalFunction: "Clinic",
    targetFunction: "Specialty clinic",
    constructionYear: 2000,
    grossFloorArea: 4800,
    strategyType: "medium_renovation",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 3200,
    durationMonths: 15,
    summary: "Medical gas and HVAC pressurization upgrades for specialty clinic met code without structural intervention.",
    lessons: ["Pressurized HVAC zones for clinic rooms", "Medical gas riser routing conflict with existing shafts"],
    tags: ["medium-renovation", "healthcare", "lanzhou", "mep"],
  },
  {
    id: "case-22",
    title: "Xiamen Colonial Villa Heritage Hotel",
    location: "Xiamen",
    region: "华南",
    buildingType: "Heritage",
    structureType: "Brick and timber colonial",
    originalFunction: "Residential villa",
    targetFunction: "Heritage boutique hotel",
    constructionYear: 1920,
    grossFloorArea: 2100,
    strategyType: "adaptive_reuse",
    outcome: "success",
    costLevel: "high",
    costPerSqm: 6500,
    durationMonths: 28,
    summary: "Reversible interventions and concealed MEP achieved hotel function while passing heritage board review.",
    lessons: ["Heritage board rejected visible AC units on street facade", "Reversible fixings required for all new steel"],
    tags: ["adaptive-reuse", "heritage", "xiamen", "mep", "structure"],
  },
  {
    id: "case-23",
    title: "Zhengzhou Metro-adjacent Retail Podium",
    location: "Zhengzhou",
    region: "华中",
    buildingType: "Commercial",
    structureType: "Reinforced concrete frame",
    originalFunction: "Retail podium",
    targetFunction: "Food and beverage cluster",
    constructionYear: 2010,
    grossFloorArea: 9500,
    strategyType: "medium_renovation",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 2550,
    durationMonths: 12,
    summary: "Grease exhaust, fire suppression, and structural check for rooftop equipment enabled F&B conversion.",
    lessons: ["Grease duct routing conflict with residential tower above", "Rooftop equipment load check required"],
    tags: ["medium-renovation", "commercial", "zhengzhou", "fire", "mep"],
  },
  {
    id: "case-24",
    title: "Changsha Riverfront Silo Arts Center",
    location: "Changsha",
    region: "华中",
    buildingType: "Industrial",
    structureType: "Reinforced concrete silo",
    originalFunction: "Grain silo",
    targetFunction: "Arts center",
    constructionYear: 1975,
    grossFloorArea: 7800,
    strategyType: "deep_recreation",
    outcome: "partial",
    costLevel: "high",
    costPerSqm: 4400,
    durationMonths: 30,
    summary: "Circular silo cutting and new floor inserts created dramatic gallery volumes but required extensive structural modeling.",
    lessons: ["Circular silo cutting needs nonlinear analysis", "Acoustic treatment added 12% to fit-out cost"],
    failureReasons: ["Structural model iteration added 3 months to design phase"],
    tags: ["deep-recreation", "industrial", "changsha", "structure"],
  },
  {
    id: "case-25",
    title: "Ningbo Port Worker Housing Renewal",
    location: "Ningbo",
    region: "华东",
    buildingType: "Residential",
    structureType: "Brick concrete",
    originalFunction: "Worker dormitory",
    targetFunction: "Affordable rental housing",
    constructionYear: 1983,
    grossFloorArea: 5200,
    strategyType: "light_renewal",
    outcome: "success",
    costLevel: "low",
    costPerSqm: 1350,
    durationMonths: 10,
    summary: "Unit subdivision, plumbing riser replacement, and facade insulation met affordable housing standards.",
    lessons: ["Riser replacement in occupied building needs phasing", "Unit subdivision triggered fire egress recalculation"],
    tags: ["light-renewal", "residential", "ningbo", "mep", "fire"],
  },
  {
    id: "case-26",
    title: "Guiyang Mountain Hotel Retrofit",
    location: "Guiyang",
    region: "西南",
    buildingType: "Hotel",
    structureType: "Reinforced concrete frame on slope",
    originalFunction: "Hotel",
    targetFunction: "Eco-resort hotel",
    constructionYear: 1999,
    grossFloorArea: 10200,
    strategyType: "facade_upgrade",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 2100,
    durationMonths: 14,
    summary: "Envelope and hot water system upgrade achieved eco-certification without changing room count.",
    lessons: ["Solar hot water integration with existing boiler plant", "Slope drainage repair bundled with envelope work"],
    tags: ["facade", "energy", "hotel", "guiyang", "mep"],
  },
  {
    id: "case-27",
    title: "Jinan University Lab Building Upgrade",
    location: "Jinan",
    region: "华东",
    buildingType: "Educational",
    structureType: "Reinforced concrete frame",
    originalFunction: "Teaching labs",
    targetFunction: "Research labs",
    constructionYear: 1996,
    grossFloorArea: 8800,
    strategyType: "medium_renovation",
    outcome: "success",
    costLevel: "high",
    costPerSqm: 3800,
    durationMonths: 21,
    summary: "Ventilation, electrical capacity, and vibration isolation upgrades enabled research-grade lab conversion.",
    lessons: ["Electrical capacity upgrade required new transformer", "Vibration isolation for sensitive instruments"],
    tags: ["medium-renovation", "education", "jinan", "mep", "structure"],
  },
  {
    id: "case-28",
    title: "Shijiazhuang Prefab Panel Housing Renewal",
    location: "Shijiazhuang",
    region: "华北",
    buildingType: "Residential",
    structureType: "Precast panel",
    originalFunction: "Residential",
    targetFunction: "Senior living",
    constructionYear: 1980,
    grossFloorArea: 6400,
    strategyType: "medium_renovation",
    outcome: "partial",
    costLevel: "medium",
    costPerSqm: 2850,
    durationMonths: 17,
    summary: "Panel joint sealing, balcony enclosure, and elevator addition enabled senior living but panel connection repair was costly.",
    lessons: ["Precast panel joint inspection mandatory", "Elevator pit excavation near existing foundation needs monitoring"],
    failureReasons: ["Panel joint corrosion repair exceeded budget by 18%"],
    tags: ["medium-renovation", "residential", "shijiazhuang", "structure"],
  },
  {
    id: "case-29",
    title: "Wuxi Canal Industrial Park Phase 1",
    location: "Wuxi",
    region: "华东",
    buildingType: "Industrial",
    structureType: "Steel frame",
    originalFunction: "Machine shop",
    targetFunction: "Design office campus",
    constructionYear: 1988,
    grossFloorArea: 21000,
    strategyType: "adaptive_reuse",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 2650,
    durationMonths: 22,
    summary: "Phased conversion of three bays with shared MEP plant and new skylights achieved design campus at scale.",
    lessons: ["Shared MEP plant reduced per-bay cost", "Skylight cuts reduced artificial lighting load 30%"],
    tags: ["adaptive-reuse", "industrial", "wuxi", "mep", "energy"],
  },
  {
    id: "case-30",
    title: "Yinchuan Mosque-adjacent Community Center",
    location: "Yinchuan",
    region: "西北",
    buildingType: "Civic",
    structureType: "Brick masonry",
    originalFunction: "Community office",
    targetFunction: "Multicultural community center",
    constructionYear: 1970,
    grossFloorArea: 3100,
    strategyType: "light_renewal",
    outcome: "success",
    costLevel: "medium",
    costPerSqm: 1900,
    durationMonths: 11,
    summary: "Accessibility, acoustic privacy, and modest seismic tie improvements enabled inclusive community programming.",
    lessons: ["Acoustic privacy between prayer and activity rooms", "Masonry seismic ties low-cost but high impact"],
    tags: ["light-renewal", "civic", "yinchuan", "structure", "accessibility"],
  },
];
