import { sanitizeReportFilename, downloadBlob } from "@/lib/reports/report-filename";

/** Minimal Markdown → HTML for report PDF export */
export function markdownToHtml(markdown: string): string {
  const lines = markdown.split("\n");
  const html: string[] = [];
  let inList = false;
  let inTable = false;
  let tableRows: string[] = [];

  const flushList = () => {
    if (inList) {
      html.push("</ul>");
      inList = false;
    }
  };

  const flushTable = () => {
    if (!inTable || tableRows.length === 0) return;
    html.push("<table>");
    tableRows.forEach((row, i) => {
      const cells = row.split("|").filter((c) => c.trim()).map((c) => c.trim());
      if (cells.every((c) => /^[-:]+$/.test(c))) return;
      const tag = i === 0 ? "th" : "td";
      html.push(
        "<tr>" + cells.map((c) => `<${tag}>${inlineFormat(c)}</${tag}>`).join("") + "</tr>"
      );
    });
    html.push("</table>");
    inTable = false;
    tableRows = [];
  };

  const inlineFormat = (text: string) =>
    text
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.*?)\*/g, "<em>$1</em>")
      .replace(/`(.*?)`/g, "<code>$1</code>");

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed.startsWith("|")) {
      flushList();
      inTable = true;
      tableRows.push(trimmed);
      continue;
    } else if (inTable) {
      flushTable();
    }

    if (trimmed.startsWith("### ")) {
      flushList();
      html.push(`<h3>${inlineFormat(trimmed.slice(4))}</h3>`);
    } else if (trimmed.startsWith("## ")) {
      flushList();
      html.push(`<h2>${inlineFormat(trimmed.slice(3))}</h2>`);
    } else if (trimmed.startsWith("# ")) {
      flushList();
      html.push(`<h1>${inlineFormat(trimmed.slice(2))}</h1>`);
    } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      if (!inList) {
        html.push("<ul>");
        inList = true;
      }
      html.push(`<li>${inlineFormat(trimmed.slice(2))}</li>`);
    } else if (trimmed === "---") {
      flushList();
      html.push("<hr />");
    } else if (trimmed === "") {
      flushList();
    } else {
      flushList();
      html.push(`<p>${inlineFormat(trimmed)}</p>`);
    }
  }

  flushList();
  flushTable();
  return html.join("\n");
}

export function exportReportToPdf(title: string, markdown: string, projectName?: string) {
  const body = markdownToHtml(markdown);
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: "Georgia", "Times New Roman", serif;
      max-width: 720px;
      margin: 0 auto;
      padding: 48px 40px;
      line-height: 1.65;
      color: #1a1a1a;
      font-size: 11pt;
    }
    .header {
      border-bottom: 2px solid #b87333;
      padding-bottom: 16px;
      margin-bottom: 32px;
    }
    .brand { font-family: system-ui, sans-serif; font-size: 9pt; color: #888; letter-spacing: 0.05em; text-transform: uppercase; }
    h1 { font-size: 20pt; margin: 8px 0 4px; font-weight: 600; }
    .meta { font-size: 9pt; color: #666; font-family: system-ui, sans-serif; }
    h2 { font-size: 14pt; margin: 24px 0 8px; color: #222; border-bottom: 1px solid #eee; padding-bottom: 4px; }
    h3 { font-size: 12pt; margin: 16px 0 6px; color: #333; }
    p { margin: 0 0 10px; }
    ul { margin: 0 0 12px; padding-left: 20px; }
    li { margin-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 10pt; }
    th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
    th { background: #f5f5f5; font-weight: 600; }
    hr { border: none; border-top: 1px solid #eee; margin: 20px 0; }
    code { background: #f4f4f4; padding: 1px 4px; border-radius: 2px; font-size: 9pt; }
    .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #eee; font-size: 8pt; color: #999; font-family: system-ui, sans-serif; }
    @media print {
      body { padding: 20px; }
      @page { margin: 20mm; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">Recrete · 砼憶</div>
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">${projectName ? escapeHtml(projectName) + " · " : ""}${date}</div>
  </div>
  ${body}
  <div class="footer">Generated by Recrete — Reimagine. Renew. Recreate.</div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank", "noopener,noreferrer");

  if (!win) {
    downloadBlob(blob, `${sanitizeReportFilename(title)}.html`);
    URL.revokeObjectURL(url);
    alert(
      "Pop-ups are blocked. An HTML file was downloaded — open it and use Print → Save as PDF.\n\n弹窗被拦截。已下载 HTML 文件，打开后使用「打印 → 另存为 PDF」。"
    );
    return;
  }

  const triggerPrint = () => {
    try {
      win.focus();
      win.print();
    } catch {
      // Window may have been closed before print.
    }
  };

  win.addEventListener("load", triggerPrint);
  window.setTimeout(triggerPrint, 800);
  window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function downloadMarkdown(title: string, content: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  downloadBlob(blob, `${sanitizeReportFilename(title)}.md`);
}
