import type {
  DiagnosisItem,
  ProjectWithRelations,
  RenovationStrategy,
  ReportType,
  SiteIssue,
} from "@/types";

export function buildMockReportContent(
  project: ProjectWithRelations,
  diagnosisItems: DiagnosisItem[],
  strategies: RenovationStrategy[],
  issues: SiteIssue[],
  reportType: ReportType
): { title: string; content: string } {
  const date = new Date().toISOString().split("T")[0];
  const openIssues = issues.filter((i) => i.status === "open" || i.status === "in_progress");

  const templates: Record<ReportType, { title: string; content: string }> = {
    existing_condition_report: {
      title: `Existing Condition Report — ${project.name}`,
      content: `# Existing Condition Report

**Project:** ${project.name} (${project.code})
**Location:** ${project.location}
**Date:** ${date}
**Prepared by:** Recrete Platform

---

## 1. Executive Summary

This report summarizes the existing condition of ${project.name}, a ${project.constructionYear} ${project.structureType} ${project.buildingType.toLowerCase()} located in ${project.location}.

The building is currently ${project.currentFunction.toLowerCase()} and targeted for conversion to ${project.targetFunction.toLowerCase()}.

**Health Score:** ${project.healthScore}/100 | **Potential Score:** ${project.potentialScore}/100 | **Risk Level:** ${project.riskLevel}

## 2. Building Overview

| Attribute | Value |
|-----------|-------|
| Construction Year | ${project.constructionYear} |
| Structure Type | ${project.structureType} |
| Floor Count | ${project.floorCount} |
| Gross Floor Area | ${project.grossFloorArea.toLocaleString()} sqm |
| Original Function | ${project.originalFunction} |
| Current Function | ${project.currentFunction} |
| Target Function | ${project.targetFunction} |

## 3. Current Condition

${project.building?.currentCondition ?? "Condition assessment pending."}

## 4. Key Findings

${diagnosisItems.length > 0 ? diagnosisItems.map((d, i) => `${i + 1}. **${d.title}** (${d.category}, ${d.severity}): ${d.description}`).join("\n\n") : "No diagnosis items recorded yet."}

## 5. Open Site Issues

${openIssues.length > 0 ? openIssues.map((i) => `- **${i.title}** [${i.priority}] — ${i.location ?? "Location TBD"}`).join("\n") : "No open site issues."}

## 6. Recommendations

1. Complete structural assessment before schematic design
2. Commission hazardous materials survey
3. Update MEP load calculations for new program
4. Address urgent site issues before construction mobilization

---
*Generated by Recrete AI — ${date}*`,
    },
    diagnosis_report: {
      title: `Building Diagnosis Report — ${project.name}`,
      content: `# Building Diagnosis Report

**Project:** ${project.name} | **Date:** ${date}

## Summary

Total diagnosis items: **${diagnosisItems.length}**
Critical/High severity: **${diagnosisItems.filter((d) => d.severity === "critical" || d.severity === "high").length}**

## Diagnosis Items by Category

${Object.entries(
  diagnosisItems.reduce(
    (acc, d) => {
      acc[d.category] = acc[d.category] ?? [];
      acc[d.category].push(d);
      return acc;
    },
    {} as Record<string, DiagnosisItem[]>
  )
)
  .map(
    ([cat, items]) =>
      `### ${cat.replace(/_/g, " ").toUpperCase()}\n\n${items.map((d) => `- **${d.title}** [${d.severity}] — ${d.description}\n  - *Recommendation:* ${d.recommendation ?? "TBD"}`).join("\n\n")}`
  )
  .join("\n\n")}

---
*Generated by Recrete AI — ${date}*`,
    },
    renovation_strategy_report: {
      title: `Renovation Strategy Report — ${project.name}`,
      content: `# Renovation Strategy Report

**Project:** ${project.name} | **Date:** ${date}
**Renovation Goal:** ${project.renovationGoal}

## Strategies Evaluated

${strategies.map((s, i) => `### ${i + 1}. ${s.name}

**Type:** ${s.type.replace(/_/g, " ")}
**Summary:** ${s.summary}

| Metric | Level |
|--------|-------|
| Cost | ${s.costLevel} |
| Schedule | ${s.scheduleLevel} |
| Risk | ${s.riskLevel} |

**Pros:** ${s.pros.join("; ")}
**Cons:** ${s.cons.join("; ")}

${s.recommendationReason ? `**Recommendation:** ${s.recommendationReason}` : ""}
`).join("\n---\n\n")}

---
*Generated by Recrete AI — ${date}*`,
    },
    owner_presentation: {
      title: `Owner Presentation Outline — ${project.name}`,
      content: `# Owner Presentation Outline

**Project:** ${project.name}
**Date:** ${date}

## Slide 1: Project Vision
- Transform ${project.originalFunction.toLowerCase()} into ${project.targetFunction.toLowerCase()}
- Location: ${project.location}
- ${project.grossFloorArea.toLocaleString()} sqm opportunity

## Slide 2: Building Asset
- Built ${project.constructionYear}, ${project.structureType}
- Health: ${project.healthScore}/100 | Potential: ${project.potentialScore}/100

## Slide 3: Key Challenges
${diagnosisItems.slice(0, 4).map((d) => `- ${d.title}`).join("\n")}

## Slide 4: Recommended Strategy
${strategies.find((s) => s.recommendationReason)?.name ?? strategies[0]?.name ?? "Strategy evaluation in progress"}

## Slide 5: Next Steps
1. Approve preferred strategy direction
2. Commission detailed surveys
3. Begin schematic design phase
4. Stakeholder engagement plan

---
*Generated by Recrete AI — ${date}*`,
    },
    government_submission: {
      title: `Government Submission Draft — ${project.name}`,
      content: `# Urban Renewal Submission Draft

**Applicant:** ${project.name}
**Project Code:** ${project.code}
**Location:** ${project.location}
**Submission Date:** ${date}

## 1. Project Background
Renovation of existing ${project.buildingType.toLowerCase()} (${project.constructionYear}) for adaptive reuse as ${project.targetFunction.toLowerCase()}.

## 2. Public Benefit
- Revitalization of underutilized urban asset
- Community cultural and educational programming
- Preservation of existing structure reducing demolition waste

## 3. Technical Summary
- Structure: ${project.structureType}, ${project.floorCount} floors, ${project.grossFloorArea.toLocaleString()} sqm
- Risk assessment: ${project.riskLevel} risk level
- ${diagnosisItems.length} diagnosis items identified, ${openIssues.length} open site issues

## 4. Compliance Considerations
- Fire safety upgrade required for occupancy change
- Accessibility improvements planned
- Heritage impact: ${project.building?.heritageLevel ?? "none"}

---
*Generated by Recrete AI — ${date}*`,
    },
    site_issue_report: {
      title: `Site Issue Report — ${project.name}`,
      content: `# Site Issue Report

**Project:** ${project.name} | **Date:** ${date}
**Total Issues:** ${issues.length} | **Open:** ${openIssues.length}

## Open Issues

${openIssues.map((i) => `### ${i.title}
- **Category:** ${i.category}
- **Priority:** ${i.priority}
- **Status:** ${i.status}
- **Location:** ${i.location ?? "TBD"}
- ${i.description}
`).join("\n")}

## Resolved Issues

${issues.filter((i) => i.status === "resolved" || i.status === "closed").map((i) => `- ${i.title} [${i.status}]`).join("\n") || "None"}

---
*Generated by Recrete AI — ${date}*`,
    },
    design_meeting_summary: {
      title: `Design Meeting Summary — ${project.name}`,
      content: `# Design Meeting Summary

**Project:** ${project.name} | **Date:** ${date}
**Status:** ${project.status}

## Discussion Topics
- Diagnosis review (${diagnosisItems.length} items)
- Strategy evaluation (${strategies.length} options)
- Site issues (${openIssues.length} open)

## Decisions
- Continue with adaptive reuse evaluation
- Commission asbestos survey before demolition

## Action Items
1. Structural engineer site visit
2. Upload missing MEP drawings
3. Stakeholder workshop for program requirements

---
*Generated by Recrete AI — ${date}*`,
    },
  };

  return templates[reportType];
}
